services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile

    env_file:
      - .env.local
    environment:
      PORT: 3000
      S3_ENDPOINT: http://localhost:9000
      S3_BUCKET: sboard
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
      - minio

  frontend:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:80"

volumes:
  postgres-data:
  minio-data:
